(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["uni_modules/uv-icon/components/uv-icon/uv-icon"],{2708:function(t,i,n){},77108:function(t,i,n){"use strict";n.r(i);var e=n("9805"),s=n.n(e);for(var u in e)["default"].indexOf(u)<0&&function(t){n.d(i,t,(function(){return e[t]}))}(u);i["default"]=s.a},"917f":function(t,i,n){"use strict";n.d(i,"b",(function(){return e})),n.d(i,"c",(function(){return s})),n.d(i,"a",(function(){}));var e=function(){var t=this,i=t.$createElement,n=(t._self._c,t.isImg?t.__get_style([t.imgStyle,t.$uv.addStyle(t.customStyle)]):null),e=t.isImg?null:t.__get_style([t.iconStyle,t.$uv.addStyle(t.customStyle)]),s=""!==t.label?t.$uv.addUnit(t.labelSize):null,u=""!==t.label&&"right"==t.labelPos?t.$uv.addUnit(t.space):null,o=""!==t.label&&"bottom"==t.labelPos?t.$uv.addUnit(t.space):null,l=""!==t.label&&"left"==t.labelPos?t.$uv.addUnit(t.space):null,a=""!==t.label&&"top"==t.labelPos?t.$uv.addUnit(t.space):null;t.$mp.data=Object.assign({},{$root:{s0:n,s1:e,g0:s,g1:u,g2:o,g3:l,g4:a}})},s=[]},9805:function(t,i,n){"use strict";var e=n("47a9");Object.defineProperty(i,"__esModule",{value:!0}),i.default=void 0;var s=e(n("afbc")),u=e(n("4d2e")),o=e(n("3256")),l=e(n("7ee5")),a={name:"uv-icon",emits:["click"],mixins:[s.default,u.default,l.default],data:function(){return{colorType:["primary","success","info","error","warning"]}},computed:{uClasses:function(){var t=[];return t.push(this.customPrefix),t.push(this.customPrefix+"-"+this.name),this.color&&this.colorType.includes(this.color)&&t.push("uv-icon__icon--"+this.color),t},iconStyle:function(){var t={};return t={fontSize:this.$uv.addUnit(this.size),lineHeight:this.$uv.addUnit(this.size),fontWeight:this.bold?"bold":"normal",top:this.$uv.addUnit(this.top)},this.color&&!this.colorType.includes(this.color)&&(t.color=this.color),t},isImg:function(){return-1!==this.name.indexOf("/")},imgStyle:function(){var t={};return t.width=this.width?this.$uv.addUnit(this.width):this.$uv.addUnit(this.size),t.height=this.height?this.$uv.addUnit(this.height):this.$uv.addUnit(this.size),t},icon:function(){var t=o.default["uvicon-"+this.name];return t?unescape("%u".concat(t)):["uvicon"].indexOf(this.customPrefix)>-1?this.name:""}},methods:{clickHandler:function(t){this.$emit("click",this.index),this.stop&&this.preventEvent(t)}}};i.default=a},bb2f:function(t,i,n){"use strict";n.r(i);var e=n("917f"),s=n("77108");for(var u in s)["default"].indexOf(u)<0&&function(t){n.d(i,t,(function(){return s[t]}))}(u);n("bd67");var o=n("828b"),l=Object(o["a"])(s["default"],e["b"],e["c"],!1,null,"1bcd47e4",null,!1,e["a"],void 0);i["default"]=l.exports},bd67:function(t,i,n){"use strict";var e=n("2708"),s=n.n(e);s.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'uni_modules/uv-icon/components/uv-icon/uv-icon-create-component',
    {
        'uni_modules/uv-icon/components/uv-icon/uv-icon-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('df3c')['createComponent'](__webpack_require__("bb2f"))
        })
    },
    [['uni_modules/uv-icon/components/uv-icon/uv-icon-create-component']]
]);
