(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/privacy-popup/privacy-popup"],{"14ef":function(t,n,i){},"29e3":function(t,n,i){"use strict";i.r(n);var e=i("4fc2"),o=i.n(e);for(var a in e)["default"].indexOf(a)<0&&function(t){i.d(n,t,(function(){return e[t]}))}(a);n["default"]=o.a},"4fc2":function(t,n,i){"use strict";(function(t,i){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var e={name:"PrivacyPopup",data:function(){return{privacyContractName:"",showPrivacy:!1,isRead:!1,resolvePrivacyAuthorization:null}},mounted:function(){var n=this;t.onNeedPrivacyAuthorization&&t.onNeedPrivacyAuthorization((function(t){n.resolvePrivacyAuthorization=t})),t.getPrivacySetting&&t.getPrivacySetting({success:function(t){console.log(t,"getPrivacySetting"),t.needAuthorization&&(n.privacyContractName=t.privacyContractName,n.showPrivacy=!0)}})},methods:{openPrivacyContract:function(){var n=this;t.openPrivacyContract({success:function(){n.isRead=!0},fail:function(){i.showToast({title:"遇到错误",icon:"error"})}})},exitMiniProgram:function(){t.exitMiniProgram()},handleAgreePrivacyAuthorization:function(){this.showPrivacy=!1,"function"===typeof this.resolvePrivacyAuthorization&&this.resolvePrivacyAuthorization({buttonId:"agree-btn",event:"agree"})}}};n.default=e}).call(this,i("3223")["default"],i("df3c")["default"])},"560a":function(t,n,i){"use strict";var e=i("14ef"),o=i.n(e);o.a},e4d5:function(t,n,i){"use strict";i.d(n,"b",(function(){return e})),i.d(n,"c",(function(){return o})),i.d(n,"a",(function(){}));var e=function(){var t=this.$createElement;this._self._c},o=[]},fb93:function(t,n,i){"use strict";i.r(n);var e=i("e4d5"),o=i("29e3");for(var a in o)["default"].indexOf(a)<0&&function(t){i.d(n,t,(function(){return o[t]}))}(a);i("560a");var r=i("828b"),c=Object(r["a"])(o["default"],e["b"],e["c"],!1,null,null,null,!1,e["a"],void 0);n["default"]=c.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/privacy-popup/privacy-popup-create-component',
    {
        'components/privacy-popup/privacy-popup-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('df3c')['createComponent'](__webpack_require__("fb93"))
        })
    },
    [['components/privacy-popup/privacy-popup-create-component']]
]);
