(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["uni_modules/uv-overlay/components/uv-overlay/uv-overlay"],{"0881":function(t,n,e){},"0f57":function(t,n,e){"use strict";e.r(n);var u=e("aae8"),i=e.n(u);for(var o in u)["default"].indexOf(o)<0&&function(t){e.d(n,t,(function(){return u[t]}))}(o);n["default"]=i.a},aae8:function(t,n,e){"use strict";var u=e("47a9");Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var i=u(e("afbc")),o=u(e("4d2e")),a=u(e("fd03")),r={name:"uv-overlay",emits:["click"],mixins:[i.default,o.default,a.default],watch:{show:function(t){}},computed:{overlayStyle:function(){var t={position:"fixed",top:0,left:0,right:0,zIndex:this.zIndex,bottom:0,"background-color":"rgba(0, 0, 0, ".concat(this.opacity,")")};return this.$uv.deepMerge(t,this.$uv.addStyle(this.customStyle))}},methods:{clickHandler:function(){this.$emit("click")},clear:function(){}}};n.default=r},bb5f:function(t,n,e){"use strict";e.r(n);var u=e("c244"),i=e("0f57");for(var o in i)["default"].indexOf(o)<0&&function(t){e.d(n,t,(function(){return i[t]}))}(o);e("e639");var a=e("828b"),r=Object(a["a"])(i["default"],u["b"],u["c"],!1,null,"19c9b517",null,!1,u["a"],void 0);n["default"]=r.exports},c244:function(t,n,e){"use strict";e.d(n,"b",(function(){return i})),e.d(n,"c",(function(){return o})),e.d(n,"a",(function(){return u}));var u={uvTransition:function(){return Promise.all([e.e("common/vendor"),e.e("uni_modules/uv-transition/components/uv-transition/uv-transition")]).then(e.bind(null,"7cf1"))}},i=function(){var t=this.$createElement;this._self._c},o=[]},e639:function(t,n,e){"use strict";var u=e("0881"),i=e.n(u);i.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'uni_modules/uv-overlay/components/uv-overlay/uv-overlay-create-component',
    {
        'uni_modules/uv-overlay/components/uv-overlay/uv-overlay-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('df3c')['createComponent'](__webpack_require__("bb5f"))
        })
    },
    [['uni_modules/uv-overlay/components/uv-overlay/uv-overlay-create-component']]
]);
